function(tp_fetch_sbe_tool out_var)
    if (SBE_TOOL_CACHE_DIR STREQUAL "")
        set(_cache_dir "${CMAKE_CURRENT_BINARY_DIR}/_deps/sbe-tool")
    else ()
        set(_cache_dir "${SBE_TOOL_CACHE_DIR}")
    endif ()
    file(MAKE_DIRECTORY "${_cache_dir}")

    set(_groups io.aeron uk.co.real-logic org.agrona)
    set(_version "${SBE_TOOL_VERSION}")
    set(_group_found "")

    if (_version STREQUAL "")
        foreach (_group IN LISTS _groups)
            string(REPLACE "." "/" _group_path "${_group}")
            set(_meta_url "https://repo1.maven.org/maven2/${_group_path}/sbe-tool/maven-metadata.xml")
            set(_meta_file "${_cache_dir}/sbe-tool-${_group}.xml")
            file(DOWNLOAD "${_meta_url}" "${_meta_file}" STATUS _meta_status LOG _meta_log)
            list(GET _meta_status 0 _meta_code)
            if (NOT _meta_code EQUAL 0)
                continue()
            endif ()

            file(READ "${_meta_file}" _meta_xml)
            string(REGEX MATCH "<release>([^<]+)</release>" _release_match "${_meta_xml}")
            if (CMAKE_MATCH_1)
                set(_version "${CMAKE_MATCH_1}")
                set(_group_found "${_group}")
                break()
            endif ()

            string(REGEX MATCH "<latest>([^<]+)</latest>" _latest_match "${_meta_xml}")
            if (CMAKE_MATCH_1)
                set(_version "${CMAKE_MATCH_1}")
                set(_group_found "${_group}")
                break()
            endif ()
        endforeach ()
    endif ()

    if (_version STREQUAL "")
        message(FATAL_ERROR "Unable to resolve sbe-tool version from Maven metadata. Set -DSBE_TOOL_VERSION= or -DSBE_TOOL_JAR=/path/to/jar.")
    endif ()

    set(_jar "${_cache_dir}/sbe-tool-${_version}.jar")
    if (NOT EXISTS "${_jar}")
        if (_group_found STREQUAL "")
            set(_groups_to_try ${_groups})
        else ()
            set(_groups_to_try "${_group_found}")
        endif ()

        foreach (_group IN LISTS _groups_to_try)
            string(REPLACE "." "/" _group_path "${_group}")
            set(_jar_url "https://repo1.maven.org/maven2/${_group_path}/sbe-tool/${_version}/sbe-tool-${_version}.jar")
            set(_jar_tmp "${_jar}.tmp")
            file(DOWNLOAD "${_jar_url}" "${_jar_tmp}" STATUS _jar_status LOG _jar_log)
            list(GET _jar_status 0 _jar_code)
            if (_jar_code EQUAL 0)
                file(RENAME "${_jar_tmp}" "${_jar}")
                set(_group_found "${_group}")
                break()
            endif ()
            file(REMOVE "${_jar_tmp}")
        endforeach ()
    endif ()

    if (NOT EXISTS "${_jar}")
        message(FATAL_ERROR "Unable to download sbe-tool ${_version} from Maven. Set -DSBE_TOOL_JAR=/path/to/jar.")
    endif ()

    set(_agrona_version "")
    set(_pom_group "${_group_found}")
    if (_pom_group STREQUAL "")
        set(_groups_to_try ${_groups})
    else ()
        set(_groups_to_try "${_pom_group}")
    endif ()

    foreach (_group IN LISTS _groups_to_try)
        string(REPLACE "." "/" _group_path "${_group}")
        set(_pom_url "https://repo1.maven.org/maven2/${_group_path}/sbe-tool/${_version}/sbe-tool-${_version}.pom")
        set(_pom_file "${_cache_dir}/sbe-tool-${_version}.pom")
        file(DOWNLOAD "${_pom_url}" "${_pom_file}" STATUS _pom_status LOG _pom_log)
        list(GET _pom_status 0 _pom_code)
        if (NOT _pom_code EQUAL 0)
            continue()
        endif ()

        file(READ "${_pom_file}" _pom_xml)
        string(REGEX MATCH "<groupId>org\\.agrona</groupId>[^<]*<artifactId>agrona</artifactId>[^<]*<version>([^<]+)</version>"
            _agrona_match "${_pom_xml}")
        if (CMAKE_MATCH_1)
            set(_agrona_version "${CMAKE_MATCH_1}")
            break()
        endif ()
    endforeach ()

    if (_agrona_version STREQUAL "")
        set(_agrona_meta "https://repo1.maven.org/maven2/org/agrona/agrona/maven-metadata.xml")
        set(_agrona_meta_file "${_cache_dir}/agrona-metadata.xml")
        file(DOWNLOAD "${_agrona_meta}" "${_agrona_meta_file}" STATUS _agrona_status LOG _agrona_log)
        list(GET _agrona_status 0 _agrona_code)
        if (_agrona_code EQUAL 0)
            file(READ "${_agrona_meta_file}" _agrona_xml)
            string(REGEX MATCH "<release>([^<]+)</release>" _agrona_release "${_agrona_xml}")
            if (CMAKE_MATCH_1)
                set(_agrona_version "${CMAKE_MATCH_1}")
            else ()
                string(REGEX MATCH "<latest>([^<]+)</latest>" _agrona_latest "${_agrona_xml}")
                if (CMAKE_MATCH_1)
                    set(_agrona_version "${CMAKE_MATCH_1}")
                endif ()
            endif ()
        endif ()
    endif ()

    set(_agrona_jar "")
    if (NOT _agrona_version STREQUAL "")
        set(_agrona_jar "${_cache_dir}/agrona-${_agrona_version}.jar")
        if (NOT EXISTS "${_agrona_jar}")
            set(_agrona_url "https://repo1.maven.org/maven2/org/agrona/agrona/${_agrona_version}/agrona-${_agrona_version}.jar")
            set(_agrona_tmp "${_agrona_jar}.tmp")
            file(DOWNLOAD "${_agrona_url}" "${_agrona_tmp}" STATUS _agrona_dl_status LOG _agrona_dl_log)
            list(GET _agrona_dl_status 0 _agrona_dl_code)
            if (_agrona_dl_code EQUAL 0)
                file(RENAME "${_agrona_tmp}" "${_agrona_jar}")
            else ()
                file(REMOVE "${_agrona_tmp}")
                set(_agrona_jar "")
            endif ()
        endif ()
    endif ()

    if (WIN32)
        set(_cp_sep ";")
    else ()
        set(_cp_sep ":")
    endif ()
    set(_classpath "${_jar}")
    if (NOT _agrona_jar STREQUAL "")
        set(_classpath "${_jar}${_cp_sep}${_agrona_jar}")
    endif ()

    set(${out_var} "${_jar}" PARENT_SCOPE)
    set(SBE_TOOL_CLASSPATH "${_classpath}" PARENT_SCOPE)
endfunction()
